package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"

	"github.com/ZainJavedDev/gqlgen-jokes-2/controllers"
	"github.com/ZainJavedDev/gqlgen-jokes-2/graph/model"
)

// Jokes is the resolver for the jokes field.
func (r *queryResolver) Jokes(ctx context.Context) ([]*model.Joke, error) {
	// panic(fmt.Errorf("not implemented: Jokes - jokes"))
	jokes := controllers.GetAllJokes()
	return jokes, nil
}

func (r *queryResolver) Joke(ctx context.Context, id string) (*model.Joke, error) {
	jokes := controllers.GetAllJokes()
	return jokes[0], nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
//
//     func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
//     panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
//     }
