// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Joke struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

type JokeInput struct {
	Text string `json:"text"`
}
